### ISSUE TITLE
Consider adding travis shields to README

### ISSUE THREAD

**Issue by rijnb** [tomtom-international/cpp-dependencies#12]
You may wish to consider adding shields to your README to indicate successful builds and/or test coverage. (For example, check the README.md in the SpeedTools repo on how to use such shields.)

**Comment by dascandy** [comment]
Working on unittests first, adding coverage measurement, getting that working with Travis and then integrating AppVeyor for Windows support - and then I'll put that info on shields.

**Comment by dascandy** [comment]
Travis shields added for current info. AppVeyor and Coverage will follow when I get it working and the numbers are not too shameful.
