### ISSUE TITLE
Might want to compare with the features in my dependency analyser

### ISSUE THREAD

**Issue by zebmason** [tomtom-international/cpp-dependencies#31]
Just watched the Meeting C++ 2016 video.

The analyser is a Visual Studio extension / NuGet command line [DeepEnds](https://github.com/zebmason/deepends) that, for Visual C++, will scan for #include statements or slowly parse with libclang. Output options include an interactive graph file and a set of statistics.

**Comment by dascandy** [comment]
Positive points:
- Works on Linux and MacOS as well as on Windows
- Very fast. Do you have some speed information? cpp-dependencies runs on Chromium on a 3-year old i7 laptop in 5.5 seconds (after pre-caching the source code).
- Directed query commands (as it is aimed at very large projects)
- Many different forms of outliers - unused headers, unused components, highly-dependent components, large source files...
- Command-line interface allowing for multiple queries with a single analysis (for reducing CI integration time-to-run)
- More information extracted from links; you can ask for a direct include-path from one component to another and see the shortest path from A to Z with all includes causing that path to exist.

Negative points:
- No tight MSVC integration.
- No interactive graph link - in fact, viewing graphs is entirely not part of the software itself. It only does the analysis.
- No CSV output. I'm not sure what it's good for from my point of view, but it's not here.
- No HTML output.
- No Doxygen output.

The tool is currently set up to be used from a script or from a command-line, and is typically used on very large code bases so having a flat output of everything into a single file is not very useful. As you say in your documentation as well, "for a large project it is possible for this to overwhelm Doxygen".

**Comment by zebmason** [comment]
Peter

Sorry that I wasn't clearer, I thought that my analysis might be complementary to yours. My code is fast enough for my problems, i.e. it is slow as I've observed whilst running it on the [Bloomberg Development Environment](https://github.com/bloomberg/bde/issues/221) - that conversation has some links to example output. So eventually I might get around to performance improvements but nobody has actually asked me for them yet.

When I get the opportunity I was going to compile your code and have a play and see what ideas I might copy. So thought it would only be polite to let you know of my solution.
