### ISSUE TITLE
Specifying directories to exclude from the analysis

### ISSUE THREAD

**Issue by MattHerring** [tomtom-international/cpp-dependencies#32]
Hi,

I've just started using the tool an a fair sized legacy codebase and am immediately getting some interesting results (GREAT tool thanks). Unfortunately a near full version of boost is contained inside the root directory of the codebase which can't be helping the performance of the parser and is also adding noise to the results. 

It would be nice to specify a (list of) directories that should be excluded from the the analysis (including all subdirectories).

**Comment by dascandy** [comment]
Still working on the details of the implementation. One improvement currently pending is that it may speed up parsing by skipping over the whole blacklisted folder.
