### ISSUE TITLE
boost dependency necessary for Linux?

### ISSUE THREAD

**Issue by Leedehai** [tomtom-international/cpp-dependencies#45]
Great tool! The project's README says C++ Boost's Filesystem is necessary, but the file "src/FilesystemInclude.h" gives an alternative（"experimental") by a conditional directive.
On Linux, there is indeed an "experimental" directory inside GCC's include directory.
So is this necessary for Linux? Installing boost seems not a cakewalk (at least for me).

**Comment by maikelvdh** [comment]
You can indeed avoid usage of boost filesystem and use the standard library experimental filesystem instead. This can be achieved by passing to CMake `-DWITH_BOOST=OFF`.

**Comment by dascandy** [comment]
Note that Boost::Filesystem was measured to be a lot faster than GCC's native implementation, due to choices made in the underlying filesystem code. This only matters on huge projects though, 10k+ files with at least a million lines of code. It's still faster than using it on Windows, too.
