### ISSUE TITLE
Error when compiling with VS on Windows - memrchr

### ISSUE THREAD

**Issue by ipostr08** [tomtom-international/cpp-dependencies#51]
memrchr() function is a GNU extension. Input.cpp in ReadCodeFrom()

**Comment by dascandy** [comment]
There is a compile option exposed in the cmakefile that defaults to "not available" on Windows, that disables the use of this function. It removes an optimization from reading code. Did you use the CMakefiles to compile it?

**Comment by BlackStar-EoP** [comment]
Compiles for VS2017 Release without any problems. Ran cmake . in the root dir, opened the SLN, clicked build and 10 seconds later there was a binary. Which VS are you using?

**Comment by mgiaco** [comment]
@BlackStar-EoP  and the Boost.Filesystem how can I install that I have never used Boost bevor.

**Comment by dascandy** [comment]
It should use std.filesystem on VS2017.

**Comment by mgiaco** [comment]
Many thanks works perfect.
