### ISSUE TITLE
show snap installation instructions on readme?

### ISSUE THREAD

**Issue by gocarlos** [tomtom-international/cpp-dependencies#55]
i packaged cpp-dependencies as a snap app which should run on almost all linux distros: 

https://snapcraft.io/cpp-dependencies
`sudo apt install cpp-dependencies` on most linux distros 

[![Snap Status](https://build.snapcraft.io/badge/gocarlos/cpp-dependencies-snap.svg)](https://build.snapcraft.io/user/gocarlos/cpp-dependencies-snap)

**Comment by gocarlos** [comment]
official badge from the sanp store: 
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-white.svg)](https://snapcraft.io/cpp-dependencies)

**Comment by dascandy** [comment]
Nice!

It's "snap install cpp-dependencies"  - but that's really nice! Thanks!
