### ISSUE TITLE
Assertion failed in src/Input.cpp:304

### ISSUE THREAD

**Issue by Warchant** [tomtom-international/cpp-dependencies#57]
```
final level of parentheses=-1
cpp-dependencies: ../src/Input.cpp:304: void ReadCmakelist(const Configuration&, std::unordered_map<std::__cxx11::basic_string<char>, Component*>&, const boost::filesystem::path&): Assertion `parenLevel == 0 || (printf("final level of parentheses=%d\n", parenLevel), 0)' failed.
Aborted (core dumped)
```

**Comment by dascandy** [comment]
Hmm.... if this is on working code that's a bug. Can you try to reduce your CMakeList to find why it thinks the parens are not balanced?

**Comment by pmontalb** [comment]
I encountered the same issue, I'll try to get a reproduceable example

**Comment by codeling** [comment]
Same issue here. Anyone got a clue what the problem might be already?

**Comment by dascandy** [comment]
Still no idea what kind of code leads to this assert; have only seen this bug report but no examples yet.

**Comment by Warchant** [comment]
https://github.com/tomtom-international/cpp-dependencies/blob/master/src/Input.cpp#L263-L264
If number of closing parenthesis is bigger than number of opening parenthesis, and file stream is at eof, then parenLevel will be equal to -1.

**Comment by RomanValov** [comment]
Hi,

I'm experiencing the same issue. I found following subprojects used in my project caused the exception:

https://github.com/webmproject/libwebp / tag v1.2.4 (current HEAD also fails)
https://github.com/gabime/spdlog.git / tag v1.10.0 (current HEAD also fails)

based on grep results CMakeLists.txt of those projects have inconsistent number of opening and closing parens.

**Comment by PeterBindels-TomTom** [comment]
Found it. It triggers on

option(
    SPDLOG_NO_ATOMIC_LEVELS
    "prevent spdlog from using of std::atomic log levels (use only if your code never modifies log levels concurrently"
    OFF)

in spdlog. Note the unbalanced parenthesis in the comment. Will fix.

**Comment by RomanValov** [comment]
Hi, thank you for spending time fixing this. The fix is actually working for spdlog.
However it won't for libwebp. Please check #63
