### ISSUE TITLE
Clarify purpose and status of this repository

### ISSUE THREAD

**Issue by ghost** [tomtom-international/cpp-dependencies#60]
**IMPORTANT PLEASE READ: NO RESPONSE WILL RESULT IN REPO ARCHIVAL AND FINALLY DELETION**

Dear maintainer,

One important topic in our TomTom open source engineering community is to make our public organization on GitHub, as well as the repositories hosted on it, more welcoming to contributors. That process starts which making it easy for other to understand the purpose of a codebase is and how people can contribute.

In order to do so we want to learn which repo's are still actively maintained and important to keep available to the open source community and which are not. We have therefore decided to start a clean-up proces which will be done as follows:

1. Please respond to this issue **within 30 days** and provide us with the necessary information requested below.
2. If there is no reply to this issue **after these 30 days**, the repository will **be archived**
3. After your repo has been archived you have **an additional 30 days to respond and provide information** and discuss with us whether you want to revert, or keep archived status.
4. **IMPORTANT** After the above mentioned additional 30 days no response is given the repository will be removed from the TomTom-International organization or will be **DELETED**

Could you please be so kind to provide us with the following information

### Contact details
Repo owner/primary contact: [please provide email address]

### Repository details

Describe the purpose/objective of this codebase in 1-5 sentences:
[enter description here]

Please select how this repository contributes to the following (thick all that apply):
- [ ] **Internal use:** The code is used inside TomTom and there is a vested interest in long term maintenance
- [ ] **Employer branding:** Project gives an insight into the scale and problem-solving of TomTom tech.
- [ ] **Hiring:** contributors and users of the project could be attractive job candidates
- [ ] **Learning:** TomTom employees can collaborate with and learn from external experts on the topic
- [ ] **Enhancement:** the project could gain new functionality and refinement by external use and contribution
- [ ] **Product:** The project is needed to make our tech or products integrate with other products or tech stacks
- [ ] **License Compliance**
- [ ] **Fork:** Fork needed for for upstream contributions, long-term upstream collaboration or product / CI/CD pipeline dependency or other need. If this is the case you can move your fork to a new GitHub organization https://github.com/tomtom-forks. If you need access to this org reach out at the #ospo channel on slack with your TomTom Github user account.

Additional context information about the purpose of this codebase:
[enter addition info here]

## Questions?
Please respond to this issue or drop a line to <opensource@tomtom.com> mentioning this issue nr.
Or for TomTom'ers reach out on the #ospo slack channel.

Thanks so much for helping keep our public repositories up to date and welcoming to all contributors.

**Comment by PeterBindels-TomTom** [comment]
> Employer branding, Hiring, Learning, Enhancement

Used to be internal use too until we switched approach. May make a return later on.

Code base is mentioned in public talks on behalf of TomTom and it would be very jarring if they were moved or deleted.

Repo owner should be / remain myself, plus @maikelvdh
